library(tidyverse)
try(devtools::install_github("hadley/r4ds"))
install.packages("maps")
install.packages("nycflights13")
install.packages("Lahman")
install.packages("microbenchmark")
install.packages("pryr")
install.packages("ggrepel")
